jobs:
- job: copr_build
  metadata:
    targets:
    - centos-stream-8-x86_64
  trigger: pull_request
- job: tests
  metadata:
    targets:
    - centos-stream-8-x86_64
  trigger: pull_request
sources:
- path: hyphen-2.8.8.tar.gz
  url: https://git.centos.org/sources/hyphen/c8/0556c392beb59433e577e3517575801212201df6
specfile_path: SPECS/hyphen.spec
upstream_ref: c8-source-git
